2+2
2+2
smp<-read.csv2"D:\Linda2019\MOOCS\R_FUN\W1\Labs\smp1.csv"
smp<-read.csv2"D:/Linda2019/MOOCS/R_FUN/W1/Labs/smp1.csv"
smp <- read.csv2 "D:/Linda2019/MOOCS/R_FUN/W1/Labs/smp1.csv"
smp <- read.csv2 ("D:/Linda2019/MOOCS/R_FUN/W1/Labs/smp1.csv")
str(smp)
chooseCRANmirror()
utils:::menuInstallPkgs()
utils:::menuInstallPkgs()
utils:::menuInstallPkgs()
library(psy)
local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
if(nchar(pkg)) library(pkg, character.only=TRUE)})
local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
if(nchar(pkg)) library(pkg, character.only=TRUE)})
chooseCRANmirror()
utils:::menuInstallPkgs()
q()
setwd("~/mooc")
setwd("~/mooc")
setwd("~/mooc")
smp <- read.csv2("smp.csv")
smp <- read.csv2("smp2.csv")
smp <- read.csv2("smp2.csv")
smp <- read.csv2("smp2.csv")
View(smp)
names(smp)
str(smp)
summary(smp)
summary(smp$age)
smp$age
smp$age[1]
smp$age[1:10]
min(smp$age[1:10])
min(smp$age)
help(min)
min(smp$age, na.rm = TRUE)
smp$abus[1:10]
unique(smp$abus)
head(smp$abus, n=10)
length(smp$abus)
nrow(smp)
table(smp.$abus)
table(smp$abus)
table(smp$abus, useNA="always")
summary(smp$abus)
head(factor(smp$abus))
abus <- factor(smp$abus, levels = c(0,1), labels = c("Non", "Oui"))
table(abus)
table(abus, useNA = "always")
names(smp)
head(smp$n.enfant)
summary(smp$n.enfant)
table(smp$n.enfant)
table(smp$n.enfant>4)
table(smp$n.enfant<4, useNA = "always")
smp$n.enfant.cat <-factor(smp$n.enfant)
table(smp$n.enfant)
levels(smp$n.enfant.cat)
nlevels(smp$n.enfant.cat)
nlevels(smp$n.enfant.cat)[6:13] <-"5+"
nlevels(smp$n.enfant.cat)
nlevels(smp$n.enfant.cat)[6:13] <- "5+"
nlevels(smp$n.enfant.cat)[6:] <- "5+"
levels(smp$n.enfant.cat)[6:13] <- "5+"
table(smp$n.enfant.cat)
save(smp,file = "smp_v1.rda")
savehistory("commandes.R")
source('~/mooc/commandes.R')
source('~/mooc/commandes.R')
smp$age[1]
smp[1,1]
smp[1,"age"]
head(smp$prof)
head(smp$prof== "agriculteur")
table(smp$prof== "agriculteur")
which(smp$prof== "agriculteur")
smp$age[which(smp$prof== "agriculteur")]
subset(smp, smp$prof== "agriculteur", age)
subset(smp, smp$prof== "agriculteur", 1:5)
names(smp)[1:5]
subset(smp, smp$prof== "agriculteur", c(age,duree,discip,n.enfant))
subset(smp, smp$prof== "agriculteur" & n.enfant >2, c(age,duree,discip,n.enfant))
subset(smp, smp$prof== "agriculteur" & n.enfant >2 & complete.cases(duree), c(age,duree,discip,n.enfant))
table(smp$n.enfant.cat)
tab <- table(smp$n.enfant.cat)
tab
sum(tab)
tab/sum(tab)
prop.table(tab)
round(prop.table(tab))
round(prop.table(tab),3)
barplot(prop.table(tab)*100)
pie(prop.table(tab)*100)
barplot(prop.table(tab)*100, ylim = c(0,30), las=1)
barplot(prop.table(tab)*100, ylim = c(0,30), las=0)
barplot(prop.table(tab)*100, ylim = c(0,30), las=5)
barplot(prop.table(tab)*100, ylim = c(0,30), las=2)
barplot(prop.table(tab)*100, ylim = c(0,30), las=3)
barplot(prop.table(tab)*100, ylim = c(0,30), las=4)
barplot(prop.table(tab)*100, ylim = c(0,30), las=1)
summary(smp$age)
hist(smp$age)
hist(smp$age, nclass = 8)
hist(smp$age, nclass = 8, prob=TRUE)
hist(smp$age, nclass = 8, prob=TRUE, las=1)
lines(smp$age, na.rm=TRUE)
help(lines)
lines(smp$age, no.rm=TRUE)
lines(density(smp$age, na.rm=TRUE))
save(smp,file = smp_v2.rda)
save(smp,file = smp_v2.rda)
save(smp,file = "smp_v2.rda")
savehistory(commands_2.R)
savehistory("commands_2.R")
